lvgl_pc_minimal: driver_backends.c File Reference
driver_backends.c File Reference
Copyright (c) 2025 EDGEMTech Ltd.
#include <unistd.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include "lvgl/lvgl.h"
#include "simulator_util.h"
#include "simulator_settings.h"
#include "driver_backends.h"
#include "backends.h"
Functions
void driver_backends_register (void)
int driver_backends_init_backend (char *backend_name)
Initialize the specified backend in case of a display driver backend.
int driver_backends_print_supported (void)
Print supported backends Prints a list of supported backends.
int driver_backends_is_supported (char *backend_name)
Checks if a backend exists and is supported.
void driver_backends_run_loop (void)
Enter the run loop enter the run loop of the selected backend.
Variables
backend_init_t available_backends []
static backend_t * backends [sizeof(available_backends)/sizeof(available_backends[0])]
static backend_t * sel_display_backend = NULL
simulator_settings_t settings
Detailed Description
Copyright (c) 2025 EDGEMTech Ltd.
Author: EDGEMTech Ltd, Erik Tagirov (erik..nosp@m.tagi.nosp@m.rov@e.nosp@m.dgem.nosp@m.tech..nosp@m.ch)
Definition in file driver_backends.c.
Function Documentation
driver_backends_init_backend()
int driver_backends_init_backend (char * backend_name)
Initialize the specified backend in case of a display driver backend.
create the lv_display, in case of a indev driver backend create an input device
Parameters
backend_name the name of the backend to initialize FBDEV,DRM etc
Returns
0 on success, -1 on error
Definition at line 141 of file driver_backends.c.
References BACKEND_DISPLAY, BACKEND_INDEV, backends, backend_handle_t::display, display_backend_t::display, backend_t::handle, backend_handle_t::indev, display_backend_t::init_display, indev_backend_t::init_indev, backend_t::name, sel_display_backend, and backend_t::type.
Referenced by main().
driver_backends_is_supported()
int driver_backends_is_supported (char * backend_name)
Checks if a backend exists and is supported.
Parameters
backend_name the backend name to check
Returns
1 is supported, 0 not supported or invalid name
Definition at line 247 of file driver_backends.c.
References backends, and backend_t::name.
Referenced by configure_simulator().
driver_backends_print_supported()
int driver_backends_print_supported (void)
Print supported backends Prints a list of supported backends.
Returns
-1 if an error occurred, 0 on success
Definition at line 222 of file driver_backends.c.
References backends, and backend_t::name.
Referenced by configure_simulator().
driver_backends_register()
void driver_backends_register (void)
Definition at line 113 of file driver_backends.c.
References available_backends, backends, and backend_t::handle.
Referenced by configure_simulator(), and main().
driver_backends_run_loop()
void driver_backends_run_loop (void)
Enter the run loop enter the run loop of the selected backend.
Definition at line 268 of file driver_backends.c.
References display_backend_t::run_loop, and sel_display_backend.
Referenced by main().
Variable Documentation
available_backends
backend_init_t available_backends[]
Definition at line 61 of file driver_backends.c.
Referenced by driver_backends_register().
backends
backend_t* backends[sizeof(available_backends)/sizeof(available_backends[0])] static
Definition at line 94 of file driver_backends.c.
Referenced by driver_backends_init_backend(), driver_backends_is_supported(), driver_backends_print_supported(), and driver_backends_register().
sel_display_backend
backend_t* sel_display_backend = NULL static
Definition at line 97 of file driver_backends.c.
Referenced by driver_backends_init_backend(), and driver_backends_run_loop().
settings
simulator_settings_t settings
Definition at line 103 of file driver_backends.c.
Referenced by configure_simulator(), and main().