lvgl_pc_minimal: driver_backends.h File Reference
driver_backends.h File Reference
provides an abstraction to support multiple graphical driver backends at the same time without recompiling everything each time
Functions
void driver_backends_register (void)
int driver_backends_init_backend (char *backend_name)
Initialize the specified backend in case of a display driver backend.
int driver_backends_is_supported (char *backend_name)
Checks if a backend exists and is supported.
int driver_backends_print_supported (void)
Print supported backends Prints a list of supported backends.
void driver_backends_run_loop (void)
Enter the run loop enter the run loop of the selected backend.
Detailed Description
provides an abstraction to support multiple graphical driver backends at the same time without recompiling everything each time
E.g: this means LVGL can be compiled with both SDL or X11
see backend.h for the details on the interface.
see the files in display_backends directory for examples on how to use each driver
Copyright (c) 2025 EDGEMTech Ltd.
Author: EDGEMTech Ltd, Erik Tagirov (erik..nosp@m.tagi.nosp@m.rov@e.nosp@m.dgem.nosp@m.tech..nosp@m.ch)
Definition in file driver_backends.h.
Function Documentation
driver_backends_init_backend()
int driver_backends_init_backend (char * backend_name)
Initialize the specified backend in case of a display driver backend.
create the lv_display, in case of a indev driver backend create an input device
Parameters
backend_name the name of the backend to initialize FBDEV,DRM etc
Returns
0 on success, -1 on error
Definition at line 141 of file driver_backends.c.
References BACKEND_DISPLAY, BACKEND_INDEV, backends, backend_handle_t::display, display_backend_t::display, backend_t::handle, backend_handle_t::indev, display_backend_t::init_display, indev_backend_t::init_indev, backend_t::name, sel_display_backend, and backend_t::type.
Referenced by main().
driver_backends_is_supported()
int driver_backends_is_supported (char * backend_name)
Checks if a backend exists and is supported.
Parameters
backend_name the backend name to check
Returns
1 is supported, 0 not supported or invalid name
Definition at line 247 of file driver_backends.c.
References backends, and backend_t::name.
Referenced by configure_simulator().
driver_backends_print_supported()
int driver_backends_print_supported (void)
Print supported backends Prints a list of supported backends.
Returns
-1 if an error occurred, 0 on success
Definition at line 222 of file driver_backends.c.
References backends, and backend_t::name.
Referenced by configure_simulator().
driver_backends_register()
void driver_backends_register (void)
Definition at line 113 of file driver_backends.c.
References available_backends, backends, and backend_t::handle.
Referenced by configure_simulator(), and main().
driver_backends_run_loop()
void driver_backends_run_loop (void)
Enter the run loop enter the run loop of the selected backend.
Definition at line 268 of file driver_backends.c.
References display_backend_t::run_loop, and sel_display_backend.
Referenced by main().