lvgl_pc_minimal: main.c File Reference
main.c File Reference
#include <unistd.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lvgl/lvgl.h"
#include "ui/ui.h"
#include "ui/actions.h"
#include "ui/vars.h"
#include "app_runtime.h"
#include "src/lib/driver_backends.h"
#include "src/lib/simulator_util.h"
#include "src/lib/simulator_settings.h"
Macros
#define DEFAULT_DISPLAY_W "800"
#define DEFAULT_DISPLAY_H "480"
Functions
static void configure_simulator (int argc, char **argv)
Configure simulator.
static void print_lvgl_version (void)
Print LVGL version.
static void print_usage (void)
Print usage information.
static void ui_tick_timer_cb (lv_timer_t *timer)
static void ui_runtime_sync_timer_cb (lv_timer_t *timer)
Synchronize runtime data with UI native variables.
void lv_ui_example (void)
int main (int argc, char **argv)
Entry point.
void action_my_action (lv_event_t *e)
Variables
static char * selected_backend
simulator_settings_t settings
Macro Definition Documentation
DEFAULT_DISPLAY_H
#define DEFAULT_DISPLAY_H "480"
Definition at line 35 of file main.c.
Referenced by configure_simulator().
DEFAULT_DISPLAY_W
#define DEFAULT_DISPLAY_W "800"
Definition at line 34 of file main.c.
Referenced by configure_simulator().
Function Documentation
action_my_action()
void action_my_action (lv_event_t * e)
Definition at line 267 of file main.c.
configure_simulator()
void configure_simulator (int argc, char ** argv) static
Configure simulator.
Process the command-line arguments used to select backend and window options before the simulator enters the LVGL run loop.
Parameters
argc the count of arguments in argv
argv The arguments
Definition at line 116 of file main.c.
References DEFAULT_DISPLAY_H, DEFAULT_DISPLAY_W, die(), driver_backends_is_supported(), driver_backends_print_supported(), driver_backends_register(), print_lvgl_version(), print_usage(), selected_backend, and settings.
Referenced by main().
lv_ui_example()
void lv_ui_example (void) extern
Definition at line 7 of file ui_example.c.
References value_changed_event_cb().
main()
int main (int argc, char ** argv)
Entry point.
Initialize LVGL, the selected backend, the generated UI, and the application runtime before entering the backend event loop.
Parameters
argc the count of arguments in argv
argv The arguments
Definition at line 206 of file main.c.
References app_runtime_init(), app_runtime_start(), app_runtime_stop(), configure_simulator(), die(), driver_backends_init_backend(), driver_backends_register(), driver_backends_run_loop(), selected_backend, settings, ui_runtime_sync_timer_cb(), and ui_tick_timer_cb().
print_lvgl_version()
void print_lvgl_version (void) static
Print LVGL version.
Definition at line 60 of file main.c.
Referenced by configure_simulator().
print_usage()
void print_usage (void) static
Print usage information.
Definition at line 72 of file main.c.
Referenced by configure_simulator().
ui_runtime_sync_timer_cb()
void ui_runtime_sync_timer_cb (lv_timer_t * timer) static
Synchronize runtime data with UI native variables.
Read the latest application snapshot produced by the secondary C++ runtime thread and copy its values into the native variables consumed by the EEZ UI bindings from the LVGL thread.
Parameters
timer The LVGL timer instance
Definition at line 97 of file main.c.
References app_runtime_get_snapshot(), app_snapshot_t::myvar1, and set_var_myvar1().
Referenced by main().
ui_tick_timer_cb()
void ui_tick_timer_cb (lv_timer_t * timer) static
Definition at line 82 of file main.c.
Referenced by main().
Variable Documentation
selected_backend
char* selected_backend static
Definition at line 48 of file main.c.
Referenced by configure_simulator(), and main().
settings
simulator_settings_t settings extern
Definition at line 103 of file driver_backends.c.
Referenced by configure_simulator(), and main().